### ISSUE TITLE
設定が画面上部に表示される

### ISSUE THREAD

**Issue by ToE42** [Peteworden/Soleil#2]
星図において、画面右上の歯車から表示できる設定画面が画面の上部にはみでて表示される。
![image](https://github.com/user-attachments/assets/dbac7d90-3f34-49d6-a5bb-73e0c03ac895)
環境
firefox 129.0 (Arch Linux)
firefox 132.0 (Android 13) でも確認

**Comment by Peteworden** [comment]
わお初めて見た、firefoxは試したことなかった
ずっと放置してるけどiPad+Chromeやと表示される範囲が変（最初右上に小さくなってたり、動かすと左にはみ出たり、いじってるうちに直ったり）という問題は前からあったので、それを直したときに上にはみ出る問題も直るか見たい
11月中にできるかな...
